routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard.home');
});

Route::get('/charts', function () {
    return view('dashboard.charts');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
  Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
    Route::get('home', 'DashboardController@index')->name('home');
    Route::group(['prefix' => 'chart', 'as' => 'chart.'], function () {
      Route::get('user', 'DashboardController@totalUserChart')->name('user');
      Route::get('revenue', 'DashboardController@revenueChart')->name('revenue');
      Route::get('checkout', 'DashboardController@abandonCheckoutChart')->name('checkout');
      Route::get('order', 'DashboardController@averageOrderChart')->name('order');
      Route::get('transaction', 'DashboardController@totalTransactionChart')->name('transaction');
      Route::get('paid', 'DashboardController@paidUserChart')->name('paid');
    });
  });
  Route::group(['prefix' => 'data', 'as' => 'data.'], function () {
    Route::get('user/{startDate}/{endDate}', 'ChartDataController@totalUser')->name('user');
    Route::get('revenue/{startDate}/{endDate}', 'ChartDataController@revenue')->name('revenue');
    Route::get('checkout/{startDate}/{endDate}', 'ChartDataController@abandonCheckout')->name('checkout');
    Route::get('order/{startDate}/{endDate}', 'ChartDataController@averageOrder')->name('order');
    Route::get('transaction/{startDate}/{endDate}', 'ChartDataController@totalTransaction')->name('transaction');
    Route::get('paid/{startDate}/{endDate}', 'ChartDataController@paidUser')->name('paid');
  });
  Route::get('login', 'Auth\LoginController@showAdminLoginForm')->name('login.form');
  Route::post('login', 'Auth\LoginController@loginAdmin')->name('login.post');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.home');
    }

    public function totalUserChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.user', $data);
    }

    public function revenueChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.revenue', $data);
    }

    public function abandonCheckoutChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.checkout', $data);
    }

    public function averageOrderChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.order', $data);
    }

    public function totalTransactionChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.transaction', $data);
    }

    public function paidUserChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.paid', $data);
    }

}

resources/views/dashboard/chart/checkout.blade.php
@extends('layout/dashboard/base')

@section('title', 'Chart')

@section('extra-fonts')

@endsection

@section('prerender-js')
  <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/dist/Chart.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/samples/utils.js') }}"></script>
@endsection

@section('extra-css')
  <style>
    canvas {
      -moz-user-select: none;
      -webkit-user-select: none;
      -ms-user-select: none;
    }
  </style>
@endsection

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Chart
        <small>Abandon Checkout</small>
      </h1>
    </section>

    <section class="content">
    	<div style="width:1000px">
    		<canvas id="chart"></canvas>
    	</div>
      <br>
    	<br>
    	Chart Date Range:
      <input type="date" id="start_date" value="{{ $startDate }}">
      to
      <input type="date" id="end_date" value="{{ $endDate }}">
    	<button id="update">update</button>
    </section>

  </div>
@endsection

@section('extra-js')
  <script>
    var url = "{{ route('admin.data.checkout', ['startDate' => $startDate, 'endDate' => $endDate]) }}";
    var date = new Array();
    var label = new Array();
    var value = new Array();
    var chart;
    $(document).ready(function(){
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
        var ctx = document.getElementById('chart').getContext('2d');
        ctx.canvas.width = 1000;
        ctx.canvas.height = 300;

        var color = Chart.helpers.color;
        var cfg = {
          type: 'bar',
          data: {
            labels: date,
            datasets: [{
              label: 'New Abandon Checkout',
              backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
              borderColor: window.chartColors.red,
              data: value,
              type: 'line',
              pointRadius: 0,
              fill: false,
              lineTension: 0,
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              xAxes: [{
                distribution: 'series',
                ticks: {
                  source: 'data',
                  autoSkip: true
                }
              }],
              yAxes: [{
                ticks: {
                  callback: function(value) {if (value % 1 === 0) {return value;}}
                },
                scaleLabel: {
                  display: true,
                  labelString: 'Value'
                }
              }]
            },
            tooltips: {
              intersect: false,
              mode: 'index',
              callbacks: {
                beginAtZero: true,
                label: function(tooltipItem, myData) {
                  var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                  if (label) {
                    label += ': ';
                  }
                  label += tooltipItem.value;
                  return label;
                }
              }
            }
          }
        };

        chart = new Chart(ctx, cfg);
      });
    });

    document.getElementById('update').addEventListener('click', function() {
      var start_date = document.getElementById('start_date').value;
      var end_date = document.getElementById('end_date').value;
      var url = "{{ route('admin.data.checkout', ['startDate' => ':startDate', 'endDate' => ':endDate']) }}";
      url = url.replace(':startDate', start_date);
      url = url.replace(':endDate', end_date);
      var date = new Array();
      var label = new Array();
      var value = new Array();
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
      chart.config.data.labels = date;
      chart.config.data.datasets[0].data = value;
      chart.update();
      });
    });
  </script>
@endsection

resources/views/dashboard/chart/order.blade.php
@extends('layout/dashboard/base')

@section('title', 'Chart')

@section('extra-fonts')

@endsection

@section('prerender-js')
  <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/dist/Chart.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/samples/utils.js') }}"></script>
@endsection

@section('extra-css')
  <style>
    canvas {
      -moz-user-select: none;
      -webkit-user-select: none;
      -ms-user-select: none;
    }
  </style>
@endsection

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Chart
        <small>Average Order</small>
      </h1>
    </section>

    <section class="content">
    	<div style="width:1000px">
    		<canvas id="chart"></canvas>
    	</div>
      <br>
    	<br>
    	Chart Date Range:
      <input type="date" id="start_date" value="{{ $startDate }}">
      to
      <input type="date" id="end_date" value="{{ $endDate }}">
    	<button id="update">update</button>
    </section>

  </div>
@endsection

@section('extra-js')
  <script>
    var url = "{{ route('admin.data.order', ['startDate' => $startDate, 'endDate' => $endDate]) }}";
    var date = new Array();
    var label = new Array();
    var value = new Array();
    var chart;
    $(document).ready(function(){
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
        var ctx = document.getElementById('chart').getContext('2d');
        ctx.canvas.width = 1000;
        ctx.canvas.height = 300;

        var color = Chart.helpers.color;
        var cfg = {
          type: 'bar',
          data: {
            labels: date,
            datasets: [{
              label: 'Average Order',
              backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
              borderColor: window.chartColors.red,
              data: value,
              type: 'line',
              pointRadius: 0,
              fill: false,
              lineTension: 0,
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              xAxes: [{
                distribution: 'series',
                ticks: {
                  source: 'data',
                  autoSkip: true
                }
              }],
              yAxes: [{
                ticks: {
                  callback: function(value, index, values) {
                    if(parseInt(value) >= 1000){
                      return 'Rp' + value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
                    } else {
                      return 'Rp' + value;
                    }
                  }
                },
                scaleLabel: {
                  display: true,
                  labelString: 'Average Order (in Rupiah)'
                }
              }]
            },
            tooltips: {
              intersect: false,
              mode: 'index',
              callbacks: {
                beginAtZero: true,
                label: function(tooltipItem, myData) {
                  var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                  if (label) {
                    label += ': ';
                  }
                  label += 'Rp' + tooltipItem.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
                  return label;
                }
              }
            }
          }
        };

        chart = new Chart(ctx, cfg);
      });
    });

    document.getElementById('update').addEventListener('click', function() {
      var start_date = document.getElementById('start_date').value;
      var end_date = document.getElementById('end_date').value;
      var url = "{{ route('admin.data.order', ['startDate' => ':startDate', 'endDate' => ':endDate']) }}";
      url = url.replace(':startDate', start_date);
      url = url.replace(':endDate', end_date);
      var date = new Array();
      var label = new Array();
      var value = new Array();
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
      chart.config.data.labels = date;
      chart.config.data.datasets[0].data = value;
      chart.update();
      });
    });
  </script>
@endsection

resources/views/dashboard/chart/paid.blade.php
@extends('layout/dashboard/base')

@section('title', 'Chart')

@section('extra-fonts')

@endsection

@section('prerender-js')
  <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/dist/Chart.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/samples/utils.js') }}"></script>
@endsection

@section('extra-css')
  <style>
    canvas {
      -moz-user-select: none;
      -webkit-user-select: none;
      -ms-user-select: none;
    }
  </style>
@endsection

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Chart
        <small>Paid User</small>
      </h1>
    </section>

    <section class="content">
    	<div style="width:1000px">
    		<canvas id="chart"></canvas>
    	</div>
      <br>
    	<br>
    	Chart Date Range:
      <input type="date" id="start_date" value="{{ $startDate }}">
      to
      <input type="date" id="end_date" value="{{ $endDate }}">
    	<button id="update">update</button>
    </section>

  </div>
@endsection

@section('extra-js')
  <script>
    var url = "{{ route('admin.data.paid', ['startDate' => $startDate, 'endDate' => $endDate]) }}";
    var date = new Array();
    var label = new Array();
    var value = new Array();
    var chart;
    $(document).ready(function(){
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
        var ctx = document.getElementById('chart').getContext('2d');
        ctx.canvas.width = 1000;
        ctx.canvas.height = 300;

        var color = Chart.helpers.color;
        var cfg = {
          type: 'bar',
          data: {
            labels: date,
            datasets: [{
              label: 'Paid Users',
              backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
              borderColor: window.chartColors.red,
              data: value,
              type: 'line',
              pointRadius: 0,
              fill: false,
              lineTension: 0,
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              xAxes: [{
                distribution: 'series',
                ticks: {
                  source: 'data',
                  autoSkip: true
                }
              }],
              yAxes: [{
                ticks: {
                  callback: function(value) {if (value % 1 === 0) {return value;}}
                },
                scaleLabel: {
                  display: true,
                  labelString: 'Number of Paid Users'
                }
              }]
            },
            tooltips: {
              intersect: false,
              mode: 'index',
              callbacks: {
                beginAtZero: true,
                label: function(tooltipItem, myData) {
                  var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                  if (label) {
                    label += ': ';
                  }
                  label += tooltipItem.value;
                  return label;
                }
              }
            }
          }
        };

        chart = new Chart(ctx, cfg);
      });
    });

    document.getElementById('update').addEventListener('click', function() {
      var start_date = document.getElementById('start_date').value;
      var end_date = document.getElementById('end_date').value;
      var url = "{{ route('admin.data.paid', ['startDate' => ':startDate', 'endDate' => ':endDate']) }}";
      url = url.replace(':startDate', start_date);
      url = url.replace(':endDate', end_date);
      var date = new Array();
      var label = new Array();
      var value = new Array();
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
      chart.config.data.labels = date;
      chart.config.data.datasets[0].data = value;
      chart.update();
      });
    });
  </script>
@endsection

resources/views/dashboard/chart/revenue.blade.php
@extends('layout/dashboard/base')

@section('title', 'Chart')

@section('extra-fonts')

@endsection

@section('prerender-js')
  <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/dist/Chart.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/samples/utils.js') }}"></script>
@endsection

@section('extra-css')
  <style>
    canvas {
      -moz-user-select: none;
      -webkit-user-select: none;
      -ms-user-select: none;
    }
  </style>
@endsection

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Chart
        <small>Revenue</small>
      </h1>
    </section>

    <section class="content">
    	<div style="width:1000px">
    		<canvas id="chart"></canvas>
    	</div>
      <br>
    	<br>
    	Chart Date Range:
      <input type="date" id="start_date" value="{{ $startDate }}">
      to
      <input type="date" id="end_date" value="{{ $endDate }}">
    	<button id="update">update</button>
    </section>

  </div>
@endsection

@section('extra-js')
  <script>
    var url = "{{ route('admin.data.revenue', ['startDate' => $startDate, 'endDate' => $endDate]) }}";
    var date = new Array();
    var label = new Array();
    var value = new Array();
    var chart;
    $(document).ready(function(){
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
        var ctx = document.getElementById('chart').getContext('2d');
        ctx.canvas.width = 1000;
        ctx.canvas.height = 300;

        var color = Chart.helpers.color;
        var cfg = {
          type: 'bar',
          data: {
            labels: date,
            datasets: [{
              label: 'Revenue',
              backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
              borderColor: window.chartColors.red,
              data: value,
              type: 'line',
              pointRadius: 0,
              fill: false,
              lineTension: 0,
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              xAxes: [{
                distribution: 'series',
                ticks: {
                  source: 'data',
                  autoSkip: true
                }
              }],
              yAxes: [{
                ticks: {
                  callback: function(value, index, values) {
                    if(parseInt(value) >= 1000){
                      return 'Rp' + value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
                    } else {
                      return 'Rp' + value;
                    }
                  }
                },
                scaleLabel: {
                  display: true,
                  labelString: 'Revenue (in Rupiah)'
                }
              }]
            },
            tooltips: {
              intersect: false,
              mode: 'index',
              callbacks: {
                beginAtZero: true,
                label: function(tooltipItem, myData) {
                  var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                  if (label) {
                    label += ': ';
                  }
                  label += 'Rp' + tooltipItem.value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
                  return label;
                }
              }
            }
          }
        };

        chart = new Chart(ctx, cfg);
      });
    });

    document.getElementById('update').addEventListener('click', function() {
      var start_date = document.getElementById('start_date').value;
      var end_date = document.getElementById('end_date').value;
      var url = "{{ route('admin.data.revenue', ['startDate' => ':startDate', 'endDate' => ':endDate']) }}";
      url = url.replace(':startDate', start_date);
      url = url.replace(':endDate', end_date);
      var date = new Array();
      var label = new Array();
      var value = new Array();
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
      chart.config.data.labels = date;
      chart.config.data.datasets[0].data = value;
      chart.update();
      });
    });
  </script>
@endsection

resources/views/dashboard/chart/transaction.blade.php
@extends('layout/dashboard/base')

@section('title', 'Chart')

@section('extra-fonts')

@endsection

@section('prerender-js')
  <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/dist/Chart.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/samples/utils.js') }}"></script>
@endsection

@section('extra-css')
  <style>
    canvas {
      -moz-user-select: none;
      -webkit-user-select: none;
      -ms-user-select: none;
    }
  </style>
@endsection

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Chart
        <small>Total Transaction</small>
      </h1>
    </section>

    <section class="content">
    	<div style="width:1000px">
    		<canvas id="chart"></canvas>
    	</div>
      <br>
    	<br>
    	Chart Date Range:
      <input type="date" id="start_date" value="{{ $startDate }}">
      to
      <input type="date" id="end_date" value="{{ $endDate }}">
    	<button id="update">update</button>
    </section>

  </div>
@endsection

@section('extra-js')
  <script>
    var url = "{{ route('admin.data.transaction', ['startDate' => $startDate, 'endDate' => $endDate]) }}";
    var date = new Array();
    var label = new Array();
    var value = new Array();
    var chart;
    $(document).ready(function(){
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
        var ctx = document.getElementById('chart').getContext('2d');
        ctx.canvas.width = 1000;
        ctx.canvas.height = 300;

        var color = Chart.helpers.color;
        var cfg = {
          type: 'bar',
          data: {
            labels: date,
            datasets: [{
              label: 'Total Transaction Today',
              backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
              borderColor: window.chartColors.red,
              data: value,
              type: 'line',
              pointRadius: 0,
              fill: false,
              lineTension: 0,
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              xAxes: [{
                distribution: 'series',
                ticks: {
                  source: 'data',
                  autoSkip: true
                }
              }],
              yAxes: [{
                ticks: {
                  callback: function(value) {if (value % 1 === 0) {return value;}}
                },
                scaleLabel: {
                  display: true,
                  labelString: 'Number of Total Transactions'
                }
              }]
            },
            tooltips: {
              intersect: false,
              mode: 'index',
              callbacks: {
                beginAtZero: true,
                label: function(tooltipItem, myData) {
                  var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                  if (label) {
                    label += ': ';
                  }
                  label += tooltipItem.value;
                  return label;
                }
              }
            }
          }
        };

        chart = new Chart(ctx, cfg);
      });
    });

    document.getElementById('update').addEventListener('click', function() {
      var start_date = document.getElementById('start_date').value;
      var end_date = document.getElementById('end_date').value;
      var url = "{{ route('admin.data.transaction', ['startDate' => ':startDate', 'endDate' => ':endDate']) }}";
      url = url.replace(':startDate', start_date);
      url = url.replace(':endDate', end_date);
      var date = new Array();
      var label = new Array();
      var value = new Array();
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
      chart.config.data.labels = date;
      chart.config.data.datasets[0].data = value;
      chart.update();
      });
    });
  </script>
@endsection

resources/views/dashboard/chart/user.blade.php
@extends('layout/dashboard/base')

@section('title', 'Chart')

@section('extra-fonts')

@endsection

@section('prerender-js')
  <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/dist/Chart.min.js') }}"></script>
  <script src="{{ asset('lib/Chart.js-2.8.0/samples/utils.js') }}"></script>
@endsection

@section('extra-css')
  <style>
    canvas {
      -moz-user-select: none;
      -webkit-user-select: none;
      -ms-user-select: none;
    }
  </style>
@endsection

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Chart
        <small>Total User</small>
      </h1>
    </section>

    <section class="content">
    	<div style="width:1000px">
    		<canvas id="chart"></canvas>
    	</div>
      <br>
    	<br>
    	Chart Date Range:
      <input type="date" id="start_date" value="{{ $startDate }}">
      to
      <input type="date" id="end_date" value="{{ $endDate }}">
    	<button id="update">update</button>
    </section>

  </div>
@endsection

@section('extra-js')
  <script>
    var url = "{{ route('admin.data.user', ['startDate' => $startDate, 'endDate' => $endDate]) }}";
    var date = new Array();
    var label = new Array();
    var value = new Array();
    var chart;
    $(document).ready(function(){
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
        var ctx = document.getElementById('chart').getContext('2d');
        ctx.canvas.width = 1000;
        ctx.canvas.height = 300;

        var color = Chart.helpers.color;
        var cfg = {
          type: 'bar',
          data: {
            labels: date,
            datasets: [{
              label: 'New Registered Users',
              backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
              borderColor: window.chartColors.red,
              data: value,
              type: 'line',
              pointRadius: 0,
              fill: false,
              lineTension: 0,
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              xAxes: [{
                distribution: 'series',
                ticks: {
                  source: 'data',
                  autoSkip: true
                }
              }],
              yAxes: [{
                ticks: {
                  callback: function(value) {if (value % 1 === 0) {return value;}}
                },
                scaleLabel: {
                  display: true,
                  labelString: 'Number of Registrations'
                }
              }]
            },
            tooltips: {
              intersect: false,
              mode: 'index',
              callbacks: {
                beginAtZero: true,
                label: function(tooltipItem, myData) {
                  var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                  if (label) {
                    label += ': ';
                  }
                  label += tooltipItem.value;
                  return label;
                }
              }
            }
          }
        };

        chart = new Chart(ctx, cfg);
      });
    });

    document.getElementById('update').addEventListener('click', function() {
      var start_date = document.getElementById('start_date').value;
      var end_date = document.getElementById('end_date').value;
      var url = "{{ route('admin.data.user', ['startDate' => ':startDate', 'endDate' => ':endDate']) }}";
      url = url.replace(':startDate', start_date);
      url = url.replace(':endDate', end_date);
      var date = new Array();
      var label = new Array();
      var value = new Array();
      $.get(url, function(response){
        response.forEach(function(data){
            date.push(data[0]);
            label.push(data.nama);
            value.push(data[1]);
        });
      chart.config.data.labels = date;
      chart.config.data.datasets[0].data = value;
      chart.update();
      });
    });
  </script>
@endsection