routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard.home');
});

Route::get('/charts', function () {
    return view('dashboard.charts');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
  Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
    Route::get('home', 'DashboardController@index')->name('home');
    Route::group(['prefix' => 'chart', 'as' => 'chart.'], function () {
      Route::get('user', 'DashboardController@totalUserChart')->name('user');
      Route::get('revenue', 'DashboardController@revenueChart')->name('revenue');
      Route::get('checkout', 'DashboardController@abandonCheckoutChart')->name('checkout');
      Route::get('order', 'DashboardController@averageOrderChart')->name('order');
      Route::get('transaction', 'DashboardController@totalTransactionChart')->name('transaction');
      Route::get('paid', 'DashboardController@paidUserChart')->name('paid');
    });
  });
  Route::group(['prefix' => 'data', 'as' => 'data.'], function () {
    Route::get('user/{startDate}/{endDate}', 'ChartDataController@totalUser')->name('user');
    Route::get('revenue/{startDate}/{endDate}', 'ChartDataController@revenue')->name('revenue');
    Route::get('checkout/{startDate}/{endDate}', 'ChartDataController@abandonCheckout')->name('checkout');
    Route::get('order/{startDate}/{endDate}', 'ChartDataController@averageOrder')->name('order');
    Route::get('transaction/{startDate}/{endDate}', 'ChartDataController@totalTransaction')->name('transaction');
    Route::get('paid/{startDate}/{endDate}', 'ChartDataController@paidUser')->name('paid');
  });
  Route::get('login', 'Auth\LoginController@showAdminLoginForm')->name('login.form');
  Route::post('login', 'Auth\LoginController@loginAdmin')->name('login.post');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.home');
    }

    public function totalUserChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.user', $data);
    }

    public function revenueChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.revenue', $data);
    }

    public function abandonCheckoutChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.checkout', $data);
    }

    public function averageOrderChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.order', $data);
    }

    public function totalTransactionChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.transaction', $data);
    }

    public function paidUserChart()
    {
        $startDate = new Carbon('first day of last month');
        $startDate = $startDate->format('Y-m-d');
        $endDate = new Carbon('last day of this month');
        $endDate = $endDate->format('Y-m-d');

        $data = [
          'startDate' => $startDate,
          'endDate' => $endDate
        ];

        return view('dashboard.chart.paid', $data);
    }

}

resources/views/layout/dashboard/_footer.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.18
  </div>
  <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
  reserved.
</footer>

resources/views/layout/dashboard/_header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>Ptr</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Pintaar</b> Dashboard</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-gears"></i>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header" style="height: auto;">
              <p>
                {{ auth()->user()->name }}
                <small>{{ auth()->user()->email }}</small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-right">
                <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">
                    Sign out
                </a>
                <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layout/dashboard/_sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset('img/Pintaar-Logo.jpg') }}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>{{ auth()->user()->name }}</p>
        <div><i class="fa fa-circle text-success"></i> {{ auth()->user()->email }}</div>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="{{ route('admin.dashboard.home') }}">
          <i class="fa fa-th"></i> <span>Home</span>
          <span class="pull-right-container">
          </span>
        </a>
      </li>
      <li class="treeview menu-open">
        <a href="">
          <i class="fa fa-pie-chart"></i>
          <span>Charts</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{ route('admin.dashboard.chart.user') }}"><i class="fa fa-circle-o"></i>Total User Chart</a></li>
          <li><a href="{{ route('admin.dashboard.chart.revenue') }}"><i class="fa fa-circle-o"></i>Revenue Chart</a></li>
          <li><a href="{{ route('admin.dashboard.chart.checkout') }}"><i class="fa fa-circle-o"></i>Abandon Checkout Chart</a></li>
          <li><a href="{{ route('admin.dashboard.chart.order') }}"><i class="fa fa-circle-o"></i>Average Order Chart</a></li>
          <li><a href="{{ route('admin.dashboard.chart.transaction') }}"><i class="fa fa-circle-o"></i>Total Transaction Chart</a></li>
          <li><a href="{{ route('admin.dashboard.chart.paid') }}"><i class="fa fa-circle-o"></i>Paid User Chart</a></li>
        </ul>
      </li>
     </ul>
  </section>
  <!-- /.sidebar -->
</aside>

resources/views/layout/dashboard/base.blade.php
<!DOCTYPE html>
<html lang="id" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
        <meta name="description" content="Pintaar Dashboard Admin">

        <title>Pintaar Dashboard | @yield('title')</title>

        <link rel="shortcut icon" href="{{ asset('img/Pintaar-Logo.jpg') }}">

        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/font-awesome/css/font-awesome.min.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/Ionicons/css/ionicons.min.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/dist/css/AdminLTE.min.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/dist/css/skins/skin-blue.min.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/morris.js/morris.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/jvectormap/jquery-jvectormap.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
        <link rel="stylesheet" href="{{ asset('lib/AdminLTE-2.4.18/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        @yield('extra-fonts')
        @yield('prerender-js')
        @yield('extra-css')
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
        @include('layout/dashboard/_header')
        @include('layout/dashboard/_sidebar')
        @yield('content')
        @include('layout/dashboard/_footer')
        </div>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/jquery/dist/jquery.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
        <script>
          $.widget.bridge('uibutton', $.ui.button);
        </script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/raphael/raphael.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/morris.js/morris.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/moment/min/moment.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/bower_components/fastclick/lib/fastclick.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/dist/js/adminlte.min.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/dist/js/pages/dashboard.js') }}"></script>
        <script src="{{ asset('lib/AdminLTE-2.4.18/dist/js/demo.js') }}"></script>

        <script src="{{ asset('js/app.js') }}"></script>

        @yield('extra-js')
    </body>
</html>